# tasks file for percona-server
---
# - name: repository | install | dependencies
#   apt:
#     name: "{{ item }}"
#     state: "{{ apt_install_state | default('latest') }}"
#     update_cache: true
#     cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
#   with_items:
#     - dirmngr
#   when: ansible_distribution == 'Debian' and ansible_distribution_version is version('9.0', '>=')
#   tags:
#     - percona-server-repository-install
#     - percona-server-repository-install-dependencies

# - name: repository | add public key
#   apt_key:
#     id: 9334A25F8507EFA5
#     keyserver: keyserver.ubuntu.com
#     state: present
#   tags:
#     - percona-server-repository-public-key

# - name: repository | add 
#   apt_repository:
#     repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
#     state: present
#     update_cache: true
#   with_items: "{{ percona_server_repositories }}"
#   tags:
#     - percona-server-repository-add

- name: repository | download apt
  get_url:
    url: https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release | lower }}_all.deb
    dest: /tmp/percona-release_latest.{{ ansible_distribution_release | lower }}_all.deb
    mode: 0755
  tags:
    - percona-server-repository-add

- name: repository | Install repo .deb package
  apt:
    deb: /tmp/percona-release_latest.{{ ansible_distribution_release | lower }}_all.deb
    update_cache: yes

- name: repository | apt-pin packages
  copy:
    src: etc/apt/preferences.d/00percona.pref
    dest: /etc/apt/preferences.d/00percona.pref
    owner: root
    group: root
    mode: 0644
  tags:
    - percona-server-repository-apt-pin
